"""empty message

Revision ID: 4445b5cf3614
Revises: 
Create Date: 2021-08-27 03:27:30.520524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4445b5cf3614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', name='gender'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', name='gender'),
               nullable=False)
    # ### end Alembic commands ###
